plugins {
    id 'java-library'
    id 'io.qameta.allure' version '2.11.2'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

def versions = [
        selenide      : '6.19.1',
        allure        : '2.21.0',
        appium        : '8.5.1',
        junit         : '5.10.0',
        slf4j         : '2.0.7',
        owner         : '1.0.12'
]

allure {
    report {
        version.set(versions.allure)
    }
    adapter {
        aspectjWeaver.set(true)
        frameworks {
            junit5 {
                adapterVersion.set(versions.allure)
            }
        }
    }
}

dependencies {
    testImplementation(
            "org.slf4j:slf4j-simple:${versions.slf4j}",
            "org.aeonbits.owner:owner:${versions.owner}",
            "org.junit.jupiter:junit-jupiter:${versions.junit}"
    )
    testImplementation(
            "com.codeborne:selenide:${versions.selenide}",
            "io.qameta.allure:allure-selenide:${versions.allure}",
            "io.appium:java-client:${versions.appium}"
    )
}

sourceCompatibility = '1.8'
targetCompatibility = '1.8'

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

tasks.withType(Test) {
    useJUnitPlatform()
    systemProperties(System.getProperties())

    testLogging {
        lifecycle {
            events "started", "skipped", "failed", "standard_error", "standard_out"
            exceptionFormat "short"
        }
    }
}

// Задача для запуска всех мобильных тестов
task mobile_test(type: Test) {
    group = "verification"
    description = "Run only MOBILE tests"
    useJUnitPlatform {
        includeTags("mobile")
    }
}

// Задача по умолчанию
test {
    useJUnitPlatform()
    description = "Default task - runs all mobile tests"
}